apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  resources:
    requests:
      storage: 6Gi
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      name: mysql2
