apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: result-server
  template:
    metadata:
      labels:
        app: result-server
    spec:
      containers:
      - name: result-server
        image: yusufinci/kube-result-server:1.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          protocol: TCP
        envFrom:
          - configMapRef:
              name: app-configmap
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
      restartPolicy: Always
          
