apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: yusufinci/kube-web-server:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        envFrom:
          - configMapRef:
              name: app-configmap
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
      restartPolicy: Always
