apiVersion: v1
kind: Service
metadata:
  name: web-server-nodeport
spec:
  type: NodePort
  selector:
    app: web-server
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 80
    nodePort: 30002
